import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Admin",
      email: "admin@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: "Puma",
        logo: "/images/logo1.png",
        description: "best seller",
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      _id: "1",
      name: "Parking Mall 1",
      City: "Delhi",
      image: "/images/p1.jpg",
      price: 120,
      TotalParkingspots: 50,
      location: "DLF Mall",
      rating: 4.5,
      numReviews: 10,
      description: "Cars/scooters/vans",
    },
    {
      _id: "2",
      name: "Parking Mall 2",
      City: "Mumbai",
      image: "/images/p1.jpg",
      price: 100,
      TotalParkingspots: 30,
      location: "City Mall",
      rating: 4.5,
      numReviews: 10,
      description: "Cars/scooters/vans",
    },
    {
      _id: "3",
      name: "Parking Mall 3",
      City: "Delhi",
      image: "/images/p1.jpg",
      price: 150,
      TotalParkingspots: 100,
      location: "C21 Mall",
      rating: 4.5,
      numReviews: 10,
      description: "Cars/scooters/vans",
    },
    {
      _id: "4",
      name: "Parking Mall 4",
      City: "Mumbai",
      image: "/images/p1.jpg",
      price: 70,
      TotalParkingspots: 50,
      location: "Emporium Mall",
      rating: 4.5,
      numReviews: 10,
      description: "Cars/scooters/vans",
    },
    {
      _id: "5",
      name: "Parking Mall 5",
      City: "Delhi",
      image: "/images/p1.jpg",
      price: 150,
      TotalParkingspots: 70,
      location: "IGI Airport Mall",
      rating: 4.5,
      numReviews: 10,
      description: "Cars/scooters/vans",
    },
    {
      _id: "6",
      name: "Parking Mall 6",
      City: "Mumbai",
      image: "/images/p1.jpg",
      price: 120,
      TotalParkingspots: 250,
      location: "SVNS Mall",
      rating: 4.5,
      numReviews: 10,
      description: "Cars/scooters/vans",
    },
  ],
};
export default data;
