const data = {
  products: [
    {
      _id: "1",
      name: "Parking Mall 1",
      location: "Delhi",
      image: "/images/p1.jpg",
      price: 120,
      ToatalParkingspots: 50,
      City: "DLF Mall",
      rating: 4.5,
      numReviews: 10,
      description: "Cars/scooters/vans",
    },
    {
      _id: "2",
      name: "Parking Mall 2",
      location: "Mumbai",
      image: "/images/p1.jpg",
      price: 100,
      ToatalParkingspots: 30,
      City: "City Mall",
      rating: 4.5,
      numReviews: 10,
      description: "Cars/scooters/vans",
    },
    {
      _id: "3",
      name: "Parking Mall 3",
      location: "Delhi",
      image: "/images/p1.jpg",
      price: 150,
      ToatalParkingspots: 100,
      City: "C21 Mall",
      rating: 4.5,
      numReviews: 10,
      description: "Cars/scooters/vans",
    },
    {
      _id: "4",
      name: "Parking Mall 4",
      location: "Mumbai",
      image: "/images/p1.jpg",
      price: 70,
      ToatalParkingspots: 50,
      City: "Emporium Mall",
      rating: 4.5,
      numReviews: 10,
      description: "Cars/scooters/vans",
    },
    {
      _id: "5",
      name: "Parking Mall 5",
      location: "Delhi",
      image: "/images/p1.jpg",
      price: 150,
      ToatalParkingspots: 70,
      City: "IGI Airport Mall",
      rating: 4.5,
      numReviews: 10,
      description: "Cars/scooters/vans",
    },
    {
      _id: "6",
      name: "Parking Mall 6",
      location: "Mumbai",
      image: "/images/p1.jpg",
      price: 120,
      ToatalParkingspots: 250,
      City: "SVNS Mall",
      rating: 4.5,
      numReviews: 10,
      description: "Cars/scooters/vans",
    },
  ],
};
export default data;
