const data = {
  products: [
    {
      _id: "1",
      name: "Parking Mall 1",
      category: "Delhi",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 50,
      brand: "DLF Mall",
      rating: 4.5,
      numReviews: 10,
      description: "Cars/scooters/vans",
    },
    {
      _id: "2",
      name: "Parking Mall 2",
      category: "Mumbai",
      image: "/images/p1.jpg",
      price: 100,
      countInStock: 30,
      brand: "City Mall",
      rating: 4.5,
      numReviews: 10,
      description: "Cars/scooters/vans",
    },
    {
      _id: "3",
      name: "Parking Mall 3",
      category: "Delhi",
      image: "/images/p1.jpg",
      price: 150,
      countInStock: 100,
      brand: "C21 Mall",
      rating: 4.5,
      numReviews: 10,
      description: "Cars/scooters/vans",
    },
    {
      _id: "4",
      name: "Parking Mall 4",
      category: "Mumbai",
      image: "/images/p1.jpg",
      price: 70,
      countInStock: 50,
      brand: "Emporium Mall",
      rating: 4.5,
      numReviews: 10,
      description: "Cars/scooters/vans",
    },
    {
      _id: "5",
      name: "Parking Mall 5",
      category: "Delhi",
      image: "/images/p1.jpg",
      price: 150,
      countInStock: 70,
      brand: "IGI Airport Mall",
      rating: 4.5,
      numReviews: 10,
      description: "Cars/scooters/vans",
    },
    {
      _id: "6",
      name: "Parking Mall 6",
      category: "Mumbai",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 250,
      brand: "SVNS Mall",
      rating: 4.5,
      numReviews: 10,
      description: "Cars/scooters/vans",
    },
  ],
};
export default data;
